#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnKy3.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
    using System.Configuration;

    [global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLNS")]
	public partial class ModelClassDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCONTRACT(CONTRACT instance);
    partial void UpdateCONTRACT(CONTRACT instance);
    partial void DeleteCONTRACT(CONTRACT instance);
    partial void InsertDEGREE(DEGREE instance);
    partial void UpdateDEGREE(DEGREE instance);
    partial void DeleteDEGREE(DEGREE instance);
    partial void InsertDEGREE_CONFIRM(DEGREE_CONFIRM instance);
    partial void UpdateDEGREE_CONFIRM(DEGREE_CONFIRM instance);
    partial void DeleteDEGREE_CONFIRM(DEGREE_CONFIRM instance);
    partial void InsertDEPARTMENT(DEPARTMENT instance);
    partial void UpdateDEPARTMENT(DEPARTMENT instance);
    partial void DeleteDEPARTMENT(DEPARTMENT instance);
    partial void InsertEMPLOYEE(EMPLOYEE instance);
    partial void UpdateEMPLOYEE(EMPLOYEE instance);
    partial void DeleteEMPLOYEE(EMPLOYEE instance);
    partial void InsertEVALUATION(EVALUATION instance);
    partial void UpdateEVALUATION(EVALUATION instance);
    partial void DeleteEVALUATION(EVALUATION instance);
    partial void InsertFEEDBACK(FEEDBACK instance);
    partial void UpdateFEEDBACK(FEEDBACK instance);
    partial void DeleteFEEDBACK(FEEDBACK instance);
    partial void InsertNOTIFICATION(NOTIFICATION instance);
    partial void UpdateNOTIFICATION(NOTIFICATION instance);
    partial void DeleteNOTIFICATION(NOTIFICATION instance);
    partial void InsertPROJECT(PROJECT instance);
    partial void UpdatePROJECT(PROJECT instance);
    partial void DeletePROJECT(PROJECT instance);
    partial void InsertPROJECT_TASK(PROJECT_TASK instance);
    partial void UpdatePROJECT_TASK(PROJECT_TASK instance);
    partial void DeletePROJECT_TASK(PROJECT_TASK instance);
    partial void InsertSALARY(SALARY instance);
    partial void UpdateSALARY(SALARY instance);
    partial void DeleteSALARY(SALARY instance);
    partial void InsertTIME_KEEP(TIME_KEEP instance);
    partial void UpdateTIME_KEEP(TIME_KEEP instance);
    partial void DeleteTIME_KEEP(TIME_KEEP instance);
    partial void InsertUSER(USER instance);
    partial void UpdateUSER(USER instance);
    partial void DeleteUSER(USER instance);
        #endregion
        public ModelClassDataContext() :
				base(ConfigurationManager.ConnectionStrings["QLNSConnectionString"].ConnectionString, mappingSource)
        {
            OnCreated();
        }

        public ModelClassDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelClassDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CONTRACT> CONTRACTs
		{
			get
			{
				return this.GetTable<CONTRACT>();
			}
		}
		
		public System.Data.Linq.Table<DEGREE> DEGREEs
		{
			get
			{
				return this.GetTable<DEGREE>();
			}
		}
		
		public System.Data.Linq.Table<DEGREE_CONFIRM> DEGREE_CONFIRMs
		{
			get
			{
				return this.GetTable<DEGREE_CONFIRM>();
			}
		}
		
		public System.Data.Linq.Table<DEPARTMENT> DEPARTMENTs
		{
			get
			{
				return this.GetTable<DEPARTMENT>();
			}
		}
		
		public System.Data.Linq.Table<EMPLOYEE> EMPLOYEEs
		{
			get
			{
				return this.GetTable<EMPLOYEE>();
			}
		}
		
		public System.Data.Linq.Table<EVALUATION> EVALUATIONs
		{
			get
			{
				return this.GetTable<EVALUATION>();
			}
		}
		
		public System.Data.Linq.Table<FEEDBACK> FEEDBACKs
		{
			get
			{
				return this.GetTable<FEEDBACK>();
			}
		}
		
		public System.Data.Linq.Table<NOTIFICATION> NOTIFICATIONs
		{
			get
			{
				return this.GetTable<NOTIFICATION>();
			}
		}
		
		public System.Data.Linq.Table<PROJECT> PROJECTs
		{
			get
			{
				return this.GetTable<PROJECT>();
			}
		}
		
		public System.Data.Linq.Table<PROJECT_TASK> PROJECT_TASKs
		{
			get
			{
				return this.GetTable<PROJECT_TASK>();
			}
		}
		
		public System.Data.Linq.Table<SALARY> SALARies
		{
			get
			{
				return this.GetTable<SALARY>();
			}
		}
		
		public System.Data.Linq.Table<TIME_KEEP> TIME_KEEPs
		{
			get
			{
				return this.GetTable<TIME_KEEP>();
			}
		}
		
		public System.Data.Linq.Table<USER> USERs
		{
			get
			{
				return this.GetTable<USER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CONTRACT")]
	public partial class CONTRACT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CONTR_NUM;
		
		private int _EMP_NUM;
		
		private System.DateTime _CONTR_SIGN_DATE;
		
		private System.DateTime _CONTR_END_DATE;
		
		private System.Nullable<decimal> _CONTR_SAL_BASE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCONTR_NUMChanging(int value);
    partial void OnCONTR_NUMChanged();
    partial void OnEMP_NUMChanging(int value);
    partial void OnEMP_NUMChanged();
    partial void OnCONTR_SIGN_DATEChanging(System.DateTime value);
    partial void OnCONTR_SIGN_DATEChanged();
    partial void OnCONTR_END_DATEChanging(System.DateTime value);
    partial void OnCONTR_END_DATEChanged();
    partial void OnCONTR_SAL_BASEChanging(System.Nullable<decimal> value);
    partial void OnCONTR_SAL_BASEChanged();
    #endregion
		
		public CONTRACT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTR_NUM", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CONTR_NUM
		{
			get
			{
				return this._CONTR_NUM;
			}
			set
			{
				if ((this._CONTR_NUM != value))
				{
					this.OnCONTR_NUMChanging(value);
					this.SendPropertyChanging();
					this._CONTR_NUM = value;
					this.SendPropertyChanged("CONTR_NUM");
					this.OnCONTR_NUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_NUM", DbType="Int NOT NULL")]
		public int EMP_NUM
		{
			get
			{
				return this._EMP_NUM;
			}
			set
			{
				if ((this._EMP_NUM != value))
				{
					this.OnEMP_NUMChanging(value);
					this.SendPropertyChanging();
					this._EMP_NUM = value;
					this.SendPropertyChanged("EMP_NUM");
					this.OnEMP_NUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTR_SIGN_DATE", DbType="Date NOT NULL")]
		public System.DateTime CONTR_SIGN_DATE
		{
			get
			{
				return this._CONTR_SIGN_DATE;
			}
			set
			{
				if ((this._CONTR_SIGN_DATE != value))
				{
					this.OnCONTR_SIGN_DATEChanging(value);
					this.SendPropertyChanging();
					this._CONTR_SIGN_DATE = value;
					this.SendPropertyChanged("CONTR_SIGN_DATE");
					this.OnCONTR_SIGN_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTR_END_DATE", DbType="Date NOT NULL")]
		public System.DateTime CONTR_END_DATE
		{
			get
			{
				return this._CONTR_END_DATE;
			}
			set
			{
				if ((this._CONTR_END_DATE != value))
				{
					this.OnCONTR_END_DATEChanging(value);
					this.SendPropertyChanging();
					this._CONTR_END_DATE = value;
					this.SendPropertyChanged("CONTR_END_DATE");
					this.OnCONTR_END_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTR_SAL_BASE", DbType="Money")]
		public System.Nullable<decimal> CONTR_SAL_BASE
		{
			get
			{
				return this._CONTR_SAL_BASE;
			}
			set
			{
				if ((this._CONTR_SAL_BASE != value))
				{
					this.OnCONTR_SAL_BASEChanging(value);
					this.SendPropertyChanging();
					this._CONTR_SAL_BASE = value;
					this.SendPropertyChanged("CONTR_SAL_BASE");
					this.OnCONTR_SAL_BASEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DEGREE")]
	public partial class DEGREE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DEG_CODE;
		
		private string _DEG_NAME;
		
		private string _DEG_DESC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDEG_CODEChanging(string value);
    partial void OnDEG_CODEChanged();
    partial void OnDEG_NAMEChanging(string value);
    partial void OnDEG_NAMEChanged();
    partial void OnDEG_DESCChanging(string value);
    partial void OnDEG_DESCChanged();
    #endregion
		
		public DEGREE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEG_CODE", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DEG_CODE
		{
			get
			{
				return this._DEG_CODE;
			}
			set
			{
				if ((this._DEG_CODE != value))
				{
					this.OnDEG_CODEChanging(value);
					this.SendPropertyChanging();
					this._DEG_CODE = value;
					this.SendPropertyChanged("DEG_CODE");
					this.OnDEG_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEG_NAME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DEG_NAME
		{
			get
			{
				return this._DEG_NAME;
			}
			set
			{
				if ((this._DEG_NAME != value))
				{
					this.OnDEG_NAMEChanging(value);
					this.SendPropertyChanging();
					this._DEG_NAME = value;
					this.SendPropertyChanged("DEG_NAME");
					this.OnDEG_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEG_DESC", DbType="NVarChar(100)")]
		public string DEG_DESC
		{
			get
			{
				return this._DEG_DESC;
			}
			set
			{
				if ((this._DEG_DESC != value))
				{
					this.OnDEG_DESCChanging(value);
					this.SendPropertyChanging();
					this._DEG_DESC = value;
					this.SendPropertyChanged("DEG_DESC");
					this.OnDEG_DESCChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DEGREE_CONFIRM")]
	public partial class DEGREE_CONFIRM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DEG_CODE;
		
		private int _EMP_NUM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDEG_CODEChanging(string value);
    partial void OnDEG_CODEChanged();
    partial void OnEMP_NUMChanging(int value);
    partial void OnEMP_NUMChanged();
    #endregion
		
		public DEGREE_CONFIRM()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEG_CODE", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DEG_CODE
		{
			get
			{
				return this._DEG_CODE;
			}
			set
			{
				if ((this._DEG_CODE != value))
				{
					this.OnDEG_CODEChanging(value);
					this.SendPropertyChanging();
					this._DEG_CODE = value;
					this.SendPropertyChanged("DEG_CODE");
					this.OnDEG_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_NUM", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int EMP_NUM
		{
			get
			{
				return this._EMP_NUM;
			}
			set
			{
				if ((this._EMP_NUM != value))
				{
					this.OnEMP_NUMChanging(value);
					this.SendPropertyChanging();
					this._EMP_NUM = value;
					this.SendPropertyChanged("EMP_NUM");
					this.OnEMP_NUMChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DEPARTMENT")]
	public partial class DEPARTMENT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DEPT_CODE;
		
		private string _DEPT_NAME;
		
		private int _EMP_NUM;
		
		private string _DEPT_ADDRESS;
		
		private string _DEPT_DESC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDEPT_CODEChanging(string value);
    partial void OnDEPT_CODEChanged();
    partial void OnDEPT_NAMEChanging(string value);
    partial void OnDEPT_NAMEChanged();
    partial void OnEMP_NUMChanging(int value);
    partial void OnEMP_NUMChanged();
    partial void OnDEPT_ADDRESSChanging(string value);
    partial void OnDEPT_ADDRESSChanged();
    partial void OnDEPT_DESCChanging(string value);
    partial void OnDEPT_DESCChanged();
    #endregion
		
		public DEPARTMENT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_CODE", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DEPT_CODE
		{
			get
			{
				return this._DEPT_CODE;
			}
			set
			{
				if ((this._DEPT_CODE != value))
				{
					this.OnDEPT_CODEChanging(value);
					this.SendPropertyChanging();
					this._DEPT_CODE = value;
					this.SendPropertyChanged("DEPT_CODE");
					this.OnDEPT_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_NAME", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string DEPT_NAME
		{
			get
			{
				return this._DEPT_NAME;
			}
			set
			{
				if ((this._DEPT_NAME != value))
				{
					this.OnDEPT_NAMEChanging(value);
					this.SendPropertyChanging();
					this._DEPT_NAME = value;
					this.SendPropertyChanged("DEPT_NAME");
					this.OnDEPT_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_NUM", DbType="Int NOT NULL")]
		public int EMP_NUM
		{
			get
			{
				return this._EMP_NUM;
			}
			set
			{
				if ((this._EMP_NUM != value))
				{
					this.OnEMP_NUMChanging(value);
					this.SendPropertyChanging();
					this._EMP_NUM = value;
					this.SendPropertyChanged("EMP_NUM");
					this.OnEMP_NUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_ADDRESS", DbType="NVarChar(50)")]
		public string DEPT_ADDRESS
		{
			get
			{
				return this._DEPT_ADDRESS;
			}
			set
			{
				if ((this._DEPT_ADDRESS != value))
				{
					this.OnDEPT_ADDRESSChanging(value);
					this.SendPropertyChanging();
					this._DEPT_ADDRESS = value;
					this.SendPropertyChanged("DEPT_ADDRESS");
					this.OnDEPT_ADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_DESC", DbType="NVarChar(200)")]
		public string DEPT_DESC
		{
			get
			{
				return this._DEPT_DESC;
			}
			set
			{
				if ((this._DEPT_DESC != value))
				{
					this.OnDEPT_DESCChanging(value);
					this.SendPropertyChanging();
					this._DEPT_DESC = value;
					this.SendPropertyChanged("DEPT_DESC");
					this.OnDEPT_DESCChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EMPLOYEE")]
	public partial class EMPLOYEE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EMP_NUM;
		
		private string _EMP_NAME;
		
		private string _EMP_GENDER;
		
		private System.DateTime _EMP_DOB;
		
		private string _EMP_ADDRESS;
		
		private string _EMP_ID;
		
		private string _EMP_PLACE_OG;
		
		private string _EMP_PHONE;
		
		private string _EMP_EMAIL;
		
		private string _EMP_REL;
		
		private string _EMP_NAT;
		
		private string _EMP_POS;
		
		private string _DEPT_CODE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEMP_NUMChanging(int value);
    partial void OnEMP_NUMChanged();
    partial void OnEMP_NAMEChanging(string value);
    partial void OnEMP_NAMEChanged();
    partial void OnEMP_GENDERChanging(string value);
    partial void OnEMP_GENDERChanged();
    partial void OnEMP_DOBChanging(System.DateTime value);
    partial void OnEMP_DOBChanged();
    partial void OnEMP_ADDRESSChanging(string value);
    partial void OnEMP_ADDRESSChanged();
    partial void OnEMP_IDChanging(string value);
    partial void OnEMP_IDChanged();
    partial void OnEMP_PLACE_OGChanging(string value);
    partial void OnEMP_PLACE_OGChanged();
    partial void OnEMP_PHONEChanging(string value);
    partial void OnEMP_PHONEChanged();
    partial void OnEMP_EMAILChanging(string value);
    partial void OnEMP_EMAILChanged();
    partial void OnEMP_RELChanging(string value);
    partial void OnEMP_RELChanged();
    partial void OnEMP_NATChanging(string value);
    partial void OnEMP_NATChanged();
    partial void OnEMP_POSChanging(string value);
    partial void OnEMP_POSChanged();
    partial void OnDEPT_CODEChanging(string value);
    partial void OnDEPT_CODEChanged();
    #endregion
		
		public EMPLOYEE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_NUM", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int EMP_NUM
		{
			get
			{
				return this._EMP_NUM;
			}
			set
			{
				if ((this._EMP_NUM != value))
				{
					this.OnEMP_NUMChanging(value);
					this.SendPropertyChanging();
					this._EMP_NUM = value;
					this.SendPropertyChanged("EMP_NUM");
					this.OnEMP_NUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_NAME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EMP_NAME
		{
			get
			{
				return this._EMP_NAME;
			}
			set
			{
				if ((this._EMP_NAME != value))
				{
					this.OnEMP_NAMEChanging(value);
					this.SendPropertyChanging();
					this._EMP_NAME = value;
					this.SendPropertyChanged("EMP_NAME");
					this.OnEMP_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_GENDER", DbType="NVarChar(3) NOT NULL", CanBeNull=false)]
		public string EMP_GENDER
		{
			get
			{
				return this._EMP_GENDER;
			}
			set
			{
				if ((this._EMP_GENDER != value))
				{
					this.OnEMP_GENDERChanging(value);
					this.SendPropertyChanging();
					this._EMP_GENDER = value;
					this.SendPropertyChanged("EMP_GENDER");
					this.OnEMP_GENDERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_DOB", DbType="Date NOT NULL")]
		public System.DateTime EMP_DOB
		{
			get
			{
				return this._EMP_DOB;
			}
			set
			{
				if ((this._EMP_DOB != value))
				{
					this.OnEMP_DOBChanging(value);
					this.SendPropertyChanging();
					this._EMP_DOB = value;
					this.SendPropertyChanged("EMP_DOB");
					this.OnEMP_DOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_ADDRESS", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string EMP_ADDRESS
		{
			get
			{
				return this._EMP_ADDRESS;
			}
			set
			{
				if ((this._EMP_ADDRESS != value))
				{
					this.OnEMP_ADDRESSChanging(value);
					this.SendPropertyChanging();
					this._EMP_ADDRESS = value;
					this.SendPropertyChanged("EMP_ADDRESS");
					this.OnEMP_ADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_ID", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string EMP_ID
		{
			get
			{
				return this._EMP_ID;
			}
			set
			{
				if ((this._EMP_ID != value))
				{
					this.OnEMP_IDChanging(value);
					this.SendPropertyChanging();
					this._EMP_ID = value;
					this.SendPropertyChanged("EMP_ID");
					this.OnEMP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_PLACE_OG", DbType="NVarChar(20)")]
		public string EMP_PLACE_OG
		{
			get
			{
				return this._EMP_PLACE_OG;
			}
			set
			{
				if ((this._EMP_PLACE_OG != value))
				{
					this.OnEMP_PLACE_OGChanging(value);
					this.SendPropertyChanging();
					this._EMP_PLACE_OG = value;
					this.SendPropertyChanged("EMP_PLACE_OG");
					this.OnEMP_PLACE_OGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_PHONE", DbType="VarChar(10)")]
		public string EMP_PHONE
		{
			get
			{
				return this._EMP_PHONE;
			}
			set
			{
				if ((this._EMP_PHONE != value))
				{
					this.OnEMP_PHONEChanging(value);
					this.SendPropertyChanging();
					this._EMP_PHONE = value;
					this.SendPropertyChanged("EMP_PHONE");
					this.OnEMP_PHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_EMAIL", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string EMP_EMAIL
		{
			get
			{
				return this._EMP_EMAIL;
			}
			set
			{
				if ((this._EMP_EMAIL != value))
				{
					this.OnEMP_EMAILChanging(value);
					this.SendPropertyChanging();
					this._EMP_EMAIL = value;
					this.SendPropertyChanged("EMP_EMAIL");
					this.OnEMP_EMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_REL", DbType="NVarChar(20)")]
		public string EMP_REL
		{
			get
			{
				return this._EMP_REL;
			}
			set
			{
				if ((this._EMP_REL != value))
				{
					this.OnEMP_RELChanging(value);
					this.SendPropertyChanging();
					this._EMP_REL = value;
					this.SendPropertyChanged("EMP_REL");
					this.OnEMP_RELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_NAT", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string EMP_NAT
		{
			get
			{
				return this._EMP_NAT;
			}
			set
			{
				if ((this._EMP_NAT != value))
				{
					this.OnEMP_NATChanging(value);
					this.SendPropertyChanging();
					this._EMP_NAT = value;
					this.SendPropertyChanged("EMP_NAT");
					this.OnEMP_NATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_POS", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string EMP_POS
		{
			get
			{
				return this._EMP_POS;
			}
			set
			{
				if ((this._EMP_POS != value))
				{
					this.OnEMP_POSChanging(value);
					this.SendPropertyChanging();
					this._EMP_POS = value;
					this.SendPropertyChanged("EMP_POS");
					this.OnEMP_POSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_CODE", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string DEPT_CODE
		{
			get
			{
				return this._DEPT_CODE;
			}
			set
			{
				if ((this._DEPT_CODE != value))
				{
					this.OnDEPT_CODEChanging(value);
					this.SendPropertyChanging();
					this._DEPT_CODE = value;
					this.SendPropertyChanged("DEPT_CODE");
					this.OnDEPT_CODEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EVALUATION")]
	public partial class EVALUATION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EVAL_NUM;
		
		private int _EMP_NUM;
		
		private int _EVAL_HRDWRK;
		
		private int _EVAL_FRDLY;
		
		private int _EVAL_CRTV;
		
		private string _EVAL_CMT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEVAL_NUMChanging(int value);
    partial void OnEVAL_NUMChanged();
    partial void OnEMP_NUMChanging(int value);
    partial void OnEMP_NUMChanged();
    partial void OnEVAL_HRDWRKChanging(int value);
    partial void OnEVAL_HRDWRKChanged();
    partial void OnEVAL_FRDLYChanging(int value);
    partial void OnEVAL_FRDLYChanged();
    partial void OnEVAL_CRTVChanging(int value);
    partial void OnEVAL_CRTVChanged();
    partial void OnEVAL_CMTChanging(string value);
    partial void OnEVAL_CMTChanged();
    #endregion
		
		public EVALUATION()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVAL_NUM", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int EVAL_NUM
		{
			get
			{
				return this._EVAL_NUM;
			}
			set
			{
				if ((this._EVAL_NUM != value))
				{
					this.OnEVAL_NUMChanging(value);
					this.SendPropertyChanging();
					this._EVAL_NUM = value;
					this.SendPropertyChanged("EVAL_NUM");
					this.OnEVAL_NUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_NUM", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int EMP_NUM
		{
			get
			{
				return this._EMP_NUM;
			}
			set
			{
				if ((this._EMP_NUM != value))
				{
					this.OnEMP_NUMChanging(value);
					this.SendPropertyChanging();
					this._EMP_NUM = value;
					this.SendPropertyChanged("EMP_NUM");
					this.OnEMP_NUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVAL_HRDWRK", DbType="Int NOT NULL")]
		public int EVAL_HRDWRK
		{
			get
			{
				return this._EVAL_HRDWRK;
			}
			set
			{
				if ((this._EVAL_HRDWRK != value))
				{
					this.OnEVAL_HRDWRKChanging(value);
					this.SendPropertyChanging();
					this._EVAL_HRDWRK = value;
					this.SendPropertyChanged("EVAL_HRDWRK");
					this.OnEVAL_HRDWRKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVAL_FRDLY", DbType="Int NOT NULL")]
		public int EVAL_FRDLY
		{
			get
			{
				return this._EVAL_FRDLY;
			}
			set
			{
				if ((this._EVAL_FRDLY != value))
				{
					this.OnEVAL_FRDLYChanging(value);
					this.SendPropertyChanging();
					this._EVAL_FRDLY = value;
					this.SendPropertyChanged("EVAL_FRDLY");
					this.OnEVAL_FRDLYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVAL_CRTV", DbType="Int NOT NULL")]
		public int EVAL_CRTV
		{
			get
			{
				return this._EVAL_CRTV;
			}
			set
			{
				if ((this._EVAL_CRTV != value))
				{
					this.OnEVAL_CRTVChanging(value);
					this.SendPropertyChanging();
					this._EVAL_CRTV = value;
					this.SendPropertyChanged("EVAL_CRTV");
					this.OnEVAL_CRTVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVAL_CMT", DbType="NVarChar(200)")]
		public string EVAL_CMT
		{
			get
			{
				return this._EVAL_CMT;
			}
			set
			{
				if ((this._EVAL_CMT != value))
				{
					this.OnEVAL_CMTChanging(value);
					this.SendPropertyChanging();
					this._EVAL_CMT = value;
					this.SendPropertyChanged("EVAL_CMT");
					this.OnEVAL_CMTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FEEDBACK")]
	public partial class FEEDBACK : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FDBK_NUM;
		
		private System.DateTime _FDBK_DATE;
		
		private int _EMP_NUM;
		
		private string _FDBK_DESC;
		
		private double _FDBK_SCALE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFDBK_NUMChanging(int value);
    partial void OnFDBK_NUMChanged();
    partial void OnFDBK_DATEChanging(System.DateTime value);
    partial void OnFDBK_DATEChanged();
    partial void OnEMP_NUMChanging(int value);
    partial void OnEMP_NUMChanged();
    partial void OnFDBK_DESCChanging(string value);
    partial void OnFDBK_DESCChanged();
    partial void OnFDBK_SCALEChanging(double value);
    partial void OnFDBK_SCALEChanged();
    #endregion
		
		public FEEDBACK()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FDBK_NUM", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int FDBK_NUM
		{
			get
			{
				return this._FDBK_NUM;
			}
			set
			{
				if ((this._FDBK_NUM != value))
				{
					this.OnFDBK_NUMChanging(value);
					this.SendPropertyChanging();
					this._FDBK_NUM = value;
					this.SendPropertyChanged("FDBK_NUM");
					this.OnFDBK_NUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FDBK_DATE", DbType="Date NOT NULL")]
		public System.DateTime FDBK_DATE
		{
			get
			{
				return this._FDBK_DATE;
			}
			set
			{
				if ((this._FDBK_DATE != value))
				{
					this.OnFDBK_DATEChanging(value);
					this.SendPropertyChanging();
					this._FDBK_DATE = value;
					this.SendPropertyChanged("FDBK_DATE");
					this.OnFDBK_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_NUM", DbType="Int NOT NULL")]
		public int EMP_NUM
		{
			get
			{
				return this._EMP_NUM;
			}
			set
			{
				if ((this._EMP_NUM != value))
				{
					this.OnEMP_NUMChanging(value);
					this.SendPropertyChanging();
					this._EMP_NUM = value;
					this.SendPropertyChanged("EMP_NUM");
					this.OnEMP_NUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FDBK_DESC", DbType="NVarChar(200)")]
		public string FDBK_DESC
		{
			get
			{
				return this._FDBK_DESC;
			}
			set
			{
				if ((this._FDBK_DESC != value))
				{
					this.OnFDBK_DESCChanging(value);
					this.SendPropertyChanging();
					this._FDBK_DESC = value;
					this.SendPropertyChanged("FDBK_DESC");
					this.OnFDBK_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FDBK_SCALE", DbType="Float NOT NULL")]
		public double FDBK_SCALE
		{
			get
			{
				return this._FDBK_SCALE;
			}
			set
			{
				if ((this._FDBK_SCALE != value))
				{
					this.OnFDBK_SCALEChanging(value);
					this.SendPropertyChanging();
					this._FDBK_SCALE = value;
					this.SendPropertyChanged("FDBK_SCALE");
					this.OnFDBK_SCALEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NOTIFICATIONS")]
	public partial class NOTIFICATION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _NOTIF_NUM;
		
		private int _EMP_NUM;
		
		private System.DateTime _NOTIF_DATE;
		
		private string _NOTIF_DETAIL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNOTIF_NUMChanging(int value);
    partial void OnNOTIF_NUMChanged();
    partial void OnEMP_NUMChanging(int value);
    partial void OnEMP_NUMChanged();
    partial void OnNOTIF_DATEChanging(System.DateTime value);
    partial void OnNOTIF_DATEChanged();
    partial void OnNOTIF_DETAILChanging(string value);
    partial void OnNOTIF_DETAILChanged();
    #endregion
		
		public NOTIFICATION()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTIF_NUM", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int NOTIF_NUM
		{
			get
			{
				return this._NOTIF_NUM;
			}
			set
			{
				if ((this._NOTIF_NUM != value))
				{
					this.OnNOTIF_NUMChanging(value);
					this.SendPropertyChanging();
					this._NOTIF_NUM = value;
					this.SendPropertyChanged("NOTIF_NUM");
					this.OnNOTIF_NUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_NUM", DbType="Int NOT NULL")]
		public int EMP_NUM
		{
			get
			{
				return this._EMP_NUM;
			}
			set
			{
				if ((this._EMP_NUM != value))
				{
					this.OnEMP_NUMChanging(value);
					this.SendPropertyChanging();
					this._EMP_NUM = value;
					this.SendPropertyChanged("EMP_NUM");
					this.OnEMP_NUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTIF_DATE", DbType="Date NOT NULL")]
		public System.DateTime NOTIF_DATE
		{
			get
			{
				return this._NOTIF_DATE;
			}
			set
			{
				if ((this._NOTIF_DATE != value))
				{
					this.OnNOTIF_DATEChanging(value);
					this.SendPropertyChanging();
					this._NOTIF_DATE = value;
					this.SendPropertyChanged("NOTIF_DATE");
					this.OnNOTIF_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTIF_DETAIL", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NOTIF_DETAIL
		{
			get
			{
				return this._NOTIF_DETAIL;
			}
			set
			{
				if ((this._NOTIF_DETAIL != value))
				{
					this.OnNOTIF_DETAILChanging(value);
					this.SendPropertyChanging();
					this._NOTIF_DETAIL = value;
					this.SendPropertyChanged("NOTIF_DETAIL");
					this.OnNOTIF_DETAILChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PROJECT")]
	public partial class PROJECT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PROJ_CODE;
		
		private string _PROJ_NAME;
		
		private string _PROJ_DESC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPROJ_CODEChanging(string value);
    partial void OnPROJ_CODEChanged();
    partial void OnPROJ_NAMEChanging(string value);
    partial void OnPROJ_NAMEChanged();
    partial void OnPROJ_DESCChanging(string value);
    partial void OnPROJ_DESCChanged();
    #endregion
		
		public PROJECT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROJ_CODE", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PROJ_CODE
		{
			get
			{
				return this._PROJ_CODE;
			}
			set
			{
				if ((this._PROJ_CODE != value))
				{
					this.OnPROJ_CODEChanging(value);
					this.SendPropertyChanging();
					this._PROJ_CODE = value;
					this.SendPropertyChanged("PROJ_CODE");
					this.OnPROJ_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROJ_NAME", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string PROJ_NAME
		{
			get
			{
				return this._PROJ_NAME;
			}
			set
			{
				if ((this._PROJ_NAME != value))
				{
					this.OnPROJ_NAMEChanging(value);
					this.SendPropertyChanging();
					this._PROJ_NAME = value;
					this.SendPropertyChanged("PROJ_NAME");
					this.OnPROJ_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROJ_DESC", DbType="NVarChar(200)")]
		public string PROJ_DESC
		{
			get
			{
				return this._PROJ_DESC;
			}
			set
			{
				if ((this._PROJ_DESC != value))
				{
					this.OnPROJ_DESCChanging(value);
					this.SendPropertyChanging();
					this._PROJ_DESC = value;
					this.SendPropertyChanged("PROJ_DESC");
					this.OnPROJ_DESCChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PROJECT_TASK")]
	public partial class PROJECT_TASK : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PROJTSK_NUM;
		
		private int _EMP_NUM;
		
		private double _PROJTSK_PROG;
		
		private string _PROJTSK_DOC;
		
		private string _PROJTSK_IMG;
		
		private string _PROJTSK_DESC;
		
		private string _PROJ_CODE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPROJTSK_NUMChanging(int value);
    partial void OnPROJTSK_NUMChanged();
    partial void OnEMP_NUMChanging(int value);
    partial void OnEMP_NUMChanged();
    partial void OnPROJTSK_PROGChanging(double value);
    partial void OnPROJTSK_PROGChanged();
    partial void OnPROJTSK_DOCChanging(string value);
    partial void OnPROJTSK_DOCChanged();
    partial void OnPROJTSK_IMGChanging(string value);
    partial void OnPROJTSK_IMGChanged();
    partial void OnPROJTSK_DESCChanging(string value);
    partial void OnPROJTSK_DESCChanged();
    partial void OnPROJ_CODEChanging(string value);
    partial void OnPROJ_CODEChanged();
    #endregion
		
		public PROJECT_TASK()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROJTSK_NUM", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PROJTSK_NUM
		{
			get
			{
				return this._PROJTSK_NUM;
			}
			set
			{
				if ((this._PROJTSK_NUM != value))
				{
					this.OnPROJTSK_NUMChanging(value);
					this.SendPropertyChanging();
					this._PROJTSK_NUM = value;
					this.SendPropertyChanged("PROJTSK_NUM");
					this.OnPROJTSK_NUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_NUM", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int EMP_NUM
		{
			get
			{
				return this._EMP_NUM;
			}
			set
			{
				if ((this._EMP_NUM != value))
				{
					this.OnEMP_NUMChanging(value);
					this.SendPropertyChanging();
					this._EMP_NUM = value;
					this.SendPropertyChanged("EMP_NUM");
					this.OnEMP_NUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROJTSK_PROG", DbType="Float NOT NULL")]
		public double PROJTSK_PROG
		{
			get
			{
				return this._PROJTSK_PROG;
			}
			set
			{
				if ((this._PROJTSK_PROG != value))
				{
					this.OnPROJTSK_PROGChanging(value);
					this.SendPropertyChanging();
					this._PROJTSK_PROG = value;
					this.SendPropertyChanged("PROJTSK_PROG");
					this.OnPROJTSK_PROGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROJTSK_DOC", DbType="NVarChar(100)")]
		public string PROJTSK_DOC
		{
			get
			{
				return this._PROJTSK_DOC;
			}
			set
			{
				if ((this._PROJTSK_DOC != value))
				{
					this.OnPROJTSK_DOCChanging(value);
					this.SendPropertyChanging();
					this._PROJTSK_DOC = value;
					this.SendPropertyChanged("PROJTSK_DOC");
					this.OnPROJTSK_DOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROJTSK_IMG", DbType="NVarChar(100)")]
		public string PROJTSK_IMG
		{
			get
			{
				return this._PROJTSK_IMG;
			}
			set
			{
				if ((this._PROJTSK_IMG != value))
				{
					this.OnPROJTSK_IMGChanging(value);
					this.SendPropertyChanging();
					this._PROJTSK_IMG = value;
					this.SendPropertyChanged("PROJTSK_IMG");
					this.OnPROJTSK_IMGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROJTSK_DESC", DbType="NVarChar(200)")]
		public string PROJTSK_DESC
		{
			get
			{
				return this._PROJTSK_DESC;
			}
			set
			{
				if ((this._PROJTSK_DESC != value))
				{
					this.OnPROJTSK_DESCChanging(value);
					this.SendPropertyChanging();
					this._PROJTSK_DESC = value;
					this.SendPropertyChanged("PROJTSK_DESC");
					this.OnPROJTSK_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROJ_CODE", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string PROJ_CODE
		{
			get
			{
				return this._PROJ_CODE;
			}
			set
			{
				if ((this._PROJ_CODE != value))
				{
					this.OnPROJ_CODEChanging(value);
					this.SendPropertyChanging();
					this._PROJ_CODE = value;
					this.SendPropertyChanged("PROJ_CODE");
					this.OnPROJ_CODEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SALARY")]
	public partial class SALARY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CONTR_NUM;
		
		private System.DateTime _SAL_DATE;
		
		private System.Nullable<decimal> _SAL_INC;
		
		private System.Nullable<decimal> _SAL_BONUS;
		
		private System.Nullable<decimal> _SAL_ALLW;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCONTR_NUMChanging(int value);
    partial void OnCONTR_NUMChanged();
    partial void OnSAL_DATEChanging(System.DateTime value);
    partial void OnSAL_DATEChanged();
    partial void OnSAL_INCChanging(System.Nullable<decimal> value);
    partial void OnSAL_INCChanged();
    partial void OnSAL_BONUSChanging(System.Nullable<decimal> value);
    partial void OnSAL_BONUSChanged();
    partial void OnSAL_ALLWChanging(System.Nullable<decimal> value);
    partial void OnSAL_ALLWChanged();
    #endregion
		
		public SALARY()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTR_NUM", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CONTR_NUM
		{
			get
			{
				return this._CONTR_NUM;
			}
			set
			{
				if ((this._CONTR_NUM != value))
				{
					this.OnCONTR_NUMChanging(value);
					this.SendPropertyChanging();
					this._CONTR_NUM = value;
					this.SendPropertyChanged("CONTR_NUM");
					this.OnCONTR_NUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAL_DATE", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime SAL_DATE
		{
			get
			{
				return this._SAL_DATE;
			}
			set
			{
				if ((this._SAL_DATE != value))
				{
					this.OnSAL_DATEChanging(value);
					this.SendPropertyChanging();
					this._SAL_DATE = value;
					this.SendPropertyChanged("SAL_DATE");
					this.OnSAL_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAL_INC", DbType="Money")]
		public System.Nullable<decimal> SAL_INC
		{
			get
			{
				return this._SAL_INC;
			}
			set
			{
				if ((this._SAL_INC != value))
				{
					this.OnSAL_INCChanging(value);
					this.SendPropertyChanging();
					this._SAL_INC = value;
					this.SendPropertyChanged("SAL_INC");
					this.OnSAL_INCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAL_BONUS", DbType="Money")]
		public System.Nullable<decimal> SAL_BONUS
		{
			get
			{
				return this._SAL_BONUS;
			}
			set
			{
				if ((this._SAL_BONUS != value))
				{
					this.OnSAL_BONUSChanging(value);
					this.SendPropertyChanging();
					this._SAL_BONUS = value;
					this.SendPropertyChanged("SAL_BONUS");
					this.OnSAL_BONUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAL_ALLW", DbType="Money")]
		public System.Nullable<decimal> SAL_ALLW
		{
			get
			{
				return this._SAL_ALLW;
			}
			set
			{
				if ((this._SAL_ALLW != value))
				{
					this.OnSAL_ALLWChanging(value);
					this.SendPropertyChanging();
					this._SAL_ALLW = value;
					this.SendPropertyChanged("SAL_ALLW");
					this.OnSAL_ALLWChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TIME_KEEP")]
	public partial class TIME_KEEP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TIME_CODE;
		
		private int _EMP_NUM;
		
		private System.DateTime _TIME_DATE;
		
		private System.Nullable<System.TimeSpan> _TIME_CLK_IN;
		
		private System.Nullable<System.TimeSpan> _TIME_CLK_OUT;
		
		private float _TIME_ABST;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTIME_CODEChanging(string value);
    partial void OnTIME_CODEChanged();
    partial void OnEMP_NUMChanging(int value);
    partial void OnEMP_NUMChanged();
    partial void OnTIME_DATEChanging(System.DateTime value);
    partial void OnTIME_DATEChanged();
    partial void OnTIME_CLK_INChanging(System.Nullable<System.TimeSpan> value);
    partial void OnTIME_CLK_INChanged();
    partial void OnTIME_CLK_OUTChanging(System.Nullable<System.TimeSpan> value);
    partial void OnTIME_CLK_OUTChanged();
    partial void OnTIME_ABSTChanging(float value);
    partial void OnTIME_ABSTChanged();
    #endregion
		
		public TIME_KEEP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIME_CODE", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TIME_CODE
		{
			get
			{
				return this._TIME_CODE;
			}
			set
			{
				if ((this._TIME_CODE != value))
				{
					this.OnTIME_CODEChanging(value);
					this.SendPropertyChanging();
					this._TIME_CODE = value;
					this.SendPropertyChanged("TIME_CODE");
					this.OnTIME_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_NUM", DbType="Int NOT NULL")]
		public int EMP_NUM
		{
			get
			{
				return this._EMP_NUM;
			}
			set
			{
				if ((this._EMP_NUM != value))
				{
					this.OnEMP_NUMChanging(value);
					this.SendPropertyChanging();
					this._EMP_NUM = value;
					this.SendPropertyChanged("EMP_NUM");
					this.OnEMP_NUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIME_DATE", DbType="Date NOT NULL")]
		public System.DateTime TIME_DATE
		{
			get
			{
				return this._TIME_DATE;
			}
			set
			{
				if ((this._TIME_DATE != value))
				{
					this.OnTIME_DATEChanging(value);
					this.SendPropertyChanging();
					this._TIME_DATE = value;
					this.SendPropertyChanged("TIME_DATE");
					this.OnTIME_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIME_CLK_IN", DbType="Time")]
		public System.Nullable<System.TimeSpan> TIME_CLK_IN
		{
			get
			{
				return this._TIME_CLK_IN;
			}
			set
			{
				if ((this._TIME_CLK_IN != value))
				{
					this.OnTIME_CLK_INChanging(value);
					this.SendPropertyChanging();
					this._TIME_CLK_IN = value;
					this.SendPropertyChanged("TIME_CLK_IN");
					this.OnTIME_CLK_INChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIME_CLK_OUT", DbType="Time")]
		public System.Nullable<System.TimeSpan> TIME_CLK_OUT
		{
			get
			{
				return this._TIME_CLK_OUT;
			}
			set
			{
				if ((this._TIME_CLK_OUT != value))
				{
					this.OnTIME_CLK_OUTChanging(value);
					this.SendPropertyChanging();
					this._TIME_CLK_OUT = value;
					this.SendPropertyChanged("TIME_CLK_OUT");
					this.OnTIME_CLK_OUTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIME_ABST", DbType="Real NOT NULL")]
		public float TIME_ABST
		{
			get
			{
				return this._TIME_ABST;
			}
			set
			{
				if ((this._TIME_ABST != value))
				{
					this.OnTIME_ABSTChanging(value);
					this.SendPropertyChanging();
					this._TIME_ABST = value;
					this.SendPropertyChanged("TIME_ABST");
					this.OnTIME_ABSTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USERS")]
	public partial class USER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _USER_ID;
		
		private string _USER_PSWD;
		
		private bool _USER_STATE;
		
		private string _TOKEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUSER_IDChanging(int value);
    partial void OnUSER_IDChanged();
    partial void OnUSER_PSWDChanging(string value);
    partial void OnUSER_PSWDChanged();
    partial void OnUSER_STATEChanging(bool value);
    partial void OnUSER_STATEChanged();
    partial void OnTOKENChanging(string value);
    partial void OnTOKENChanged();
    #endregion
		
		public USER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int USER_ID
		{
			get
			{
				return this._USER_ID;
			}
			set
			{
				if ((this._USER_ID != value))
				{
					this.OnUSER_IDChanging(value);
					this.SendPropertyChanging();
					this._USER_ID = value;
					this.SendPropertyChanged("USER_ID");
					this.OnUSER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_PSWD", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
		public string USER_PSWD
		{
			get
			{
				return this._USER_PSWD;
			}
			set
			{
				if ((this._USER_PSWD != value))
				{
					this.OnUSER_PSWDChanging(value);
					this.SendPropertyChanging();
					this._USER_PSWD = value;
					this.SendPropertyChanged("USER_PSWD");
					this.OnUSER_PSWDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_STATE", DbType="Bit NOT NULL")]
		public bool USER_STATE
		{
			get
			{
				return this._USER_STATE;
			}
			set
			{
				if ((this._USER_STATE != value))
				{
					this.OnUSER_STATEChanging(value);
					this.SendPropertyChanging();
					this._USER_STATE = value;
					this.SendPropertyChanged("USER_STATE");
					this.OnUSER_STATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOKEN", DbType="VarChar(80)")]
		public string TOKEN
		{
			get
			{
				return this._TOKEN;
			}
			set
			{
				if ((this._TOKEN != value))
				{
					this.OnTOKENChanging(value);
					this.SendPropertyChanging();
					this._TOKEN = value;
					this.SendPropertyChanged("TOKEN");
					this.OnTOKENChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
